- name: Install nginx
  yum:
    name: nginx
    state: present

- name: nginx configuration for wordpress default site
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf

- name: Replace nginx configuration to set default site properly
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: insert firewalld rule for nginx
  firewalld:
    port: "{{ nginx_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes

- name: web service state
  service:
    name: nginx
    state: started
    enabled: yes
