- name: Install web service
  yum:
    name: nginx
    state: present

- name: Add configuration for default site
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf

- name: Replace configuration to set default site properly
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Insert firewalld rule for web access
  firewalld:
    port: "{{ web_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes

- name: Web service state
  service:
    name: nginx
    state: started
    enabled: yes
