- name: Create site directory
  file:
    path: "{{ site_root }}"
    state: directory

- name: Download and Unarchive Wordpress tar
  unarchive:
    src: http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    extra_opts: ['--strip-components=1']
    dest: "{{ site_root }}"
    remote_src: yes

- name: Add group
  group:
    name: "{{ group_name }}"

- name: Add user
  user:
    name: "{{ username }}"
    group: "{{ group_name }}"
    home: "{{ site_root }}"

- name: Create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: 'localhost'
    state: present

- name: Copy WordPress config file
  template:
    src: wp-config.php
    dest: "{{ site_root }}"

- name: Change ownership of WordPress installation
  file:
    path: "{{ site_root }}"
    owner: "{{ username }}"
    group: "{{ group_name }}"
    state: directory
    recurse: yes

